:monitors:
  :template_keys:
    - :name
    - :type
    - :query
    - :options
    - :tags
    - :message

  :placeholders:
    :production:
      :dbname: dbname:production
      :namespace: namespace:production
      :pagerduty_alert: "@pagerduty-prod"
      :teams_datadog_alert: "@slack-bot-datadog-alerts"
      :environment: env:production
