name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rbprettier --check '**/*.{rb,json,yml,md}'
      - run: bundle exec rubocop
  Tests:
    name: "Test with Ruby ${{ matrix.ruby }}"
    strategy:
      matrix:
        include:
          - ruby: 3.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests and create coverage
        run: bundle exec rspec

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/.resultset.json
